{
 "title": "UM",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ThreadsState",
    "label": "ThreadsState",
    "query": "NEW,TERMINATED,RUNNABLE,BLOCKED,WAITING,TIMED_WAITING,UNKNOWN"
   }
  ]
 },
 "panels": [
  {
   "title": "Server CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(sag_um_server_cpu_usage_ratio[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Total published events",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sag_um_server_publishedevents_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NonConsumedMessagesQueue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sag_um_queue_published_total - sag_um_queue_consumed_total",
     "legendFormat": "{{NonConsumed}}"
    }
   ]
  },
  {
   "title": "Threads By State",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"$ThreadsState\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JMX Scrape Seconds",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jmx_scrape_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Server Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sag_um_server_currentconnections_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Еvents In Store",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sag_um_queue_events_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Connections Queues",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sag_um_queue_currentconnections_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Events Total",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sag_um_queue_events_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Topic Published Total",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sag_um_topic_published_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PublishedConsumedMessages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "expr": "sag_um_queue_published_total", "legendFormat": "__auto" },
    { "expr": "sag_um_queue_consumed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Used disk space by Channel",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "targets": [
    { "expr": "sag_um_topic_disk_usage_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Published by Destination",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "targets": [
    { "expr": "sag_um_topic_published_total", "legendFormat": "__auto" }
   ]
  }
 ]
}