{
 "title": "MSR View 1",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Processor Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IS CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "sag_is_server_proc_cpu_percent", "legendFormat": "__auto" },
    { "expr": "sag_is_server_proc_sys_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "sag_is_server_threads", "legendFormat": "IS Server Threads {{instance}}" },
    {
     "expr": "sag_is_service_threads",
     "legendFormat": "IS Service Threads {{instance}}"
    },
    {
     "expr": "sag_is_peak_service_threads",
     "legendFormat": "IS Peak Service Threads {{instance}}"
    },
    { "expr": "sag_is_system_threads", "legendFormat": "IS System Threads {{instance}}" },
    {
     "expr": "rate(sag_is_jvm_threads_waited_count[$__rate_interval])",
     "legendFormat": "IS JVM Threads Waited Rate {{__rate_interval}}"
    },
    { "expr": "sag_is_server_jvm_thread_count", "legendFormat": "IS JVM Threads {{instance}}" },
    {
     "expr": "sag_is_server_sysload_average",
     "legendFormat": "Threads Waiting for hw resources {{instance}}"
    }
   ]
  },
  { "title": "Memory Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sag_is_used_memory_bytes",
     "legendFormat": "IS Used Memory Bytes {{instance}}"
    },
    {
     "expr": "sag_is_server_used_memory_mbytes",
     "legendFormat": "IS Server USed Memory MBytes {{instance}}"
    }
   ]
  },
  {
   "title": "Millis since last Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sag_is_jvm_gc_collection_millis",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}